### ISSUE TITLE
Where do we get the eDVS ?

### ISSUE THREAD

**Issue by sidtalia** [simondlevy/eDVS#1]
Hi, I'm interested in working with event-based cameras and this seemed like it was an interesting starting point. However, I can't find this sensor online anywhere. Could you let me know where I could get one?

Thanks,
Regards,
Sidharth.

**Comment by simondlevy** [comment]
Although the eDVS line is no longer being sold,  was able to purchase a Mini eDVS by inquiring directly at sales@inivation.com

**Comment by sidtalia** [comment]
cool. thanks!
